# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: stable
        cache: false # no point in caching if go.sum is absent

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.5.0
        args: --out-format=html > lint-report.html || echo "Lint issues found"
      id: lint

    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: golangci-lint-report
        path: lint-report.html

    - name: build
      run: |
        GOOS=windows GOARCH=amd64 go build
