# This workflow is adapted from:
# https://github.com/mvdan/github-actions-golang/blob/master/.github/workflows/test.yml

name: Test
permissions:
  contents: read
  pull-requests: read

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.x
        cache: false # disables caching if go.sum is absent
    - name: Run tests with coverage
      shell: cmd
      run: go test -v -race -covermode=atomic -coverprofile="coverage.out" ./...

    # Upload coverage.
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.out